核对配置文件

diff --git a/.github/workflows/ARMv8-Mini.yml b/.github/workflows/ARMv8-Mini.yml
--- a/.github/workflows/ARMv8-Mini.yml
+++ b/.github/workflows/ARMv8-Mini.yml
@@ -197,11 +197,17 @@ jobs:
         echo "status=success" >> ${GITHUB_OUTPUT}
 
     - name: 上传 .config 文件
-      uses: actions/upload-artifact@v4
-      with:
-        name: openwrt-config
-        path: ${{ env.OPENWRT_PATH }}/.config
-    
+        if: always()
+        run: |
+          echo "OPENWRT_PATH: $OPENWRT_PATH"
+          cd $OPENWRT_PATH
+          echo "Current directory: $(pwd)"
+          ls -l .config || echo ".config not found"
+        uses: actions/upload-artifact@v4
+        with:
+          name: openwrt-config
+          path: .config
+
     - name: 编译固件
       id: compile
       if: ${{ steps.package.outputs.status }} == 'success' && !cancelled()
